package constant

const EMAIL_UPDATE = "EMAIL_UPDATE"
const CONFIRM_TO_CHANGED_EMAIL_UPDATE = "CONFIRM_TO_CHANGED_EMAIL_UPDATE"

const STAFF_REGISTRATION = "STAFF_REGISTRATION"
const REGISTER = "REGISTRATION"
const FORGOT_PASSWORD = "FORGOT_PASSWORD"
